name: lint and validate

on:
  pull_request:
    branches: [master, main]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 'lts*' # Install the latest LTS (Long-Term Support) version

      - run: npm run format:check

      - run: npm run lint:ls
      - run: npm run lint:md
      - run: npm run lint:js
